### ISSUE TITLE
How to access Windows NTFS MFT?

### ISSUE THREAD

**Issue by Anutrix** [omerbenamram/mft#121]
I am trying to get a json dump of C:\$MFT or D:\$MFT files but get:
```
Error: A runtime error has occurred

Caused by:
    0: Failed to open file D:\$MFT
    1: Access is denied. (os error 5)
```
I know it's a permission issue not this project's issue but does anyone have any advice?

**Comment by lespea** [comment]
You can use raw copy to grab the mft (use index 0 for whatever drive you want)

https://github.com/jschicht/RawCopy

**Comment by Anutrix** [comment]
Just another tool:
https://github.com/thewhiteninja/ntfstool.

Thx anyways. I will keep looking.
