### ISSUE TITLE
Log2timeline output

### ISSUE THREAD

**Issue by dnides** [omerbenamram/mft#13]
Great tool! Can you please create a l2t output option?

Here is the spec:

https://forensicswiki.org/wiki/L2T_CSV

**Comment by omerbenamram** [comment]
I think all of the information needed is in the current CSV output.
I don't use log2timeline myself so I think an adapter between the current CSV output and this format will be preferable.

Moreover this parser dosen't assume any knowledge of the host for example (which is mentioned in the format), so I think this adapter is out of the scope of this project.
