### ISSUE TITLE
Extracting streams errors out

### ISSUE THREAD

**Issue by lespea** [omerbenamram/mft#22]
Trying this on my local mft with `-e {path}` and I get this error:

`A runtime error has occurred: The system cannot find the path specified. (os error 3)`

Running with --backtraces does not change the output.

I see that there are some files in the extraction path so my guess is it's trying to create a filename that contains invalid characters or something.

If I don't try and extract any streams then it completes normally.

**Comment by omerbenamram** [comment]
I'm not sure I could determine which code path is problematic in this case, if you could share a sample that causes this I could happily fix this :)

**Comment by lespea** [comment]
I can try to get something for you today but it might be later this week. Quite busy at work right now :(

**Comment by lespea** [comment]
Sorry for the long delay.  For whatever reason I can't get this to trigger again (with the same build).  I'll try for a bit longer but if I can't get this to happen again I'll close this issue.
